---
title: "Communities and Support"
---

As a pilot program, we are starting our services with the **Great Cranberry Island** community. While the proximity to the ocean gives stunning views from many of the homes on the island, it also means higher winds, making homes harder to fully insulate from the elements. In addition, the relatively isolated nature of the island makes it difficult to organize contractors to complete repairs and upgrades, making our coordination and support even more valuable to the community.

### Communities and Contractors

Below is the list of communities that we are both currently supporting and have plans in place to provide support for in the future.

Great Cranberry Island

Islesford

Pleasant Point

**Additional information about the contractors we commonly work with can be found below:**

Efficiency Maine: Rebates and support

Efficiency Maine’s website has additional information on federal tax credits and energy rebates available in Maine. They are a great source for finding a contractor in your area to help with any of these improvements: www.efficiencymaine.com/at-home/ 

RS Insulation: <https://rsinsulationinc.com/>

Twin City Heat Pumps: <https://www.twincityheatpumps.com/> 

Window Dressers: [www.windowdressers.org](http://www.windowdressers.org) 

#### Both of these lists will be updated as the project develops!
