project:
  execute-dir: project
  type: website
execute:
  freeze: auto
website:
  title: "Homepage"
  navbar:
    tools:
      - icon: globe2
        text: Community Energy Center
        href: https://www.coa.edu/cec/
      - icon: github
        text: Project Github Repo
        href: https://github.com/LaurieLBaker/CEDS-Energy
      
    left:
      - href: goals.qmd
        text: Our Process
      - href: communities.qmd
        text: Communities
      - href: cases.qmd
        text: Case Studies
      - href: about.qmd
        text: About
  page-footer: 
    background: gray
    left: ""
    center: "![Logo image](/logos/logos-together.png)"
    right: " "
  back-to-top-navigation: true 
format:
  html:
    theme: 
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    toc: false

editor: visual

