project:
  execute-dir: project
  type: website
execute:
  freeze: auto
website:
  google-analytics:
    tracking-id: "G-5J567MJVD0"
    anonymize-ip: true
  favicon: favicon-black.png
  title: "Home"
  navbar:
    tools:
      - icon: globe2
        text: Community Energy Center
        href: https://www.coa.edu/cec/
      
    left:
      - href: process.qmd
        text: Our Process
      - href: communities.qmd
        text: Communities
      - href: cases.qmd
        text: Case Studies
      - href: about.qmd
        text: About
    right: 
      - href: signuppage.qmd
        text: SIGN UP FOR THE PROGRAM
  page-footer:   
    left: " Contact us: 802 266 0301 <br> mdicommunityenergy@coa.edu <br> 105 Eden Street, Bar Harbor, ME, 04609"
    center: "![](logos/Logos-together.png)"
    background: "#808080"
  back-to-top-navigation: false 
format:
  html:
    theme: 
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    toc: false

editor: visual

