project:
  execute-dir: project
  type: website
execute:
  freeze: auto
website:
  title: "Homepage"
  navbar:
    tools:
      - icon: globe2
        text: Community Energy Center
        href: https://www.coa.edu/cec/
      - icon: github
        text: Project Github Repo
        href: https://github.com/LaurieLBaker/CEDS-Energy
      
    left:
      - href: process.qmd
        text: Our Process
      - href: communities.qmd
        text: Communities
      - href: cases.qmd
        text: Case Studies
      - href: about.qmd
        text: About
    right: 
      - href: signuppage.qmd
        text: SIGN UP FOR THE PROGRAM
  page-footer:   
    left: " Contact us: 802 266 0301 <br> mdicommunityenergy@coa.edu <br> 105 Eden Steert, Bar Harbor, ME, 04609"
    center: "![](/logos/logos-together.png)"
    right: ""
    background: gray
  back-to-top-navigation: true 
format:
  html:
    theme: 
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    toc: false

editor: visual

