---
title: "Communities We Work With"
---

This summer (2026) we are expanding our services to all of **Mount Desert Island**. We will also be continuing our partnership with the **Sipayik Resilience Committee**, including more free energy audits for any member of the Passamaquoddy Nation.

------------------------------------------------------------------------

[Services on Mount Desert Island]{.underline}

-   Free home energy audit & a comprehensive report with recommendations

-   Hand-off to A Climate To Thrive and their energy coaching program

-   Priority for year-round residents

*Year-round residents of MDI all qualify for a free home energy audit conducted by certified COA staff and students. After the audit, you will receive a report and in-person debrief from us detailing our findings and recommendations we have for your home, including information on financing options.*

*We offer the option to coordinate your in-person debrief with one of A Climate To Thrive's energy coaches, who can provide long-term support in implementing recommendations. Our program and A Climate To Thrive's program are **separate**, but compliment each other extremely well if you wish to participate in both.*

Sign-up for a free energy audit here: [MDI SIGN-UP](https://docs.google.com/forms/d/e/1FAIpQLSesEccMfJ2NuZcVDRGo2-6Spb1KY5zfDyObw1kBiIf8a5Se3A/viewform?usp=header)

------------------------------------------------------------------------

[Services in Sipayik]{.underline}

-   Free home energy audit & a comprehensive report with recommendations

-   In-person debrief on audit and report

-   Energy assessment walk-throughs of public buildings

-   Support with data collection and program planning for the Sipayik Resilience Committee

*Members of the Passamaquoddy Nation both on and off reservation can get a free home energy audit conducted by certified COA students. After the audit, you will receive a report and in-person debrief from us detailing our findings and recommendations we have for your home, including information on financing options.*

*We can also provide walk-through energy assessments of commercial buildings. These are less time intensive and invasive than complete audits, but can reveal opportunities for energy consumption reduction, as well as comfort and health and safety upgrades. Buildings we have done this for include the Tribal Office, the Housing Authority building, and the well site. Contact the Sipayik Resilience Committee to coordinate a walk-through.*

Sign-up for a free energy audit here: [SIPAYIK SIGN-UP](https://docs.google.com/forms/d/e/1FAIpQLScXaymzpVfAA-zBD0jpE8o2We2PFylwGJ9zf06vJL7cV4jYYw/viewform)

------------------------------------------------------------------------
